import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ApplicationKernel from "~/core/ApplicationKernel";
import Header from "~/app/views/Header/Header";
import Aside from "~/app/views/Aside";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={inter.className} suppressHydrationWarning>
        <ApplicationKernel>
          <Header />
          <div className="flex justify-center w-full">
            <div className="grid grid-cols-[256px_1fr_256px] max-w-[1280px] px-6 w-full">
              <Aside />
              {children}
            </div>
          </div>
        </ApplicationKernel>
      </body>
    </html>
  );
}
